import time
import os
import pathlib
from datetime import datetime
from collections import defaultdict, deque

PROGRESS_FILE = pathlib.Path("progress.md")
POLL_INTERVAL = 1  # seconds (short for demo; would be hours in production)


def load_processed_items():
    """Load the set of already-processed item IDs from the progress/spine file."""
    if PROGRESS_FILE.exists():
        content = PROGRESS_FILE.read_text().strip()
        if content:
            processed = set()
            lines = content.split('\n')
            for line in lines:
                line = line.strip()
                if line.startswith("- Item ") or line.startswith("- "):
                    item = line[2:].strip()
                    if item:
                        processed.add(item)
            return processed
    return set()


def save_processed_items(processed_items, graph_edges=0, adjacency=None):
    """Save the processed items and graph state to the progress/spine file."""
    timestamp = datetime.now().isoformat()
    
    # Build the processed items section
    processed_lines = []
    for item in sorted(processed_items):
        processed_lines.append(f"- {item}")
    
    # Build adjacency string for dependencies
    adj_str = ""
    if adjacency:
        for node, deps in sorted(adjacency.items()):
            deps_repr = ", ".join(f"'{d}'" for d in deps)
            adj_str += f"{node} -> [{deps_repr}]\n" if deps_repr else f"{node} -> []\n"
    
    content = f"""# Graph Loop Progress

**Last updated**: {timestamp}

**Processed Items**: {len(processed_items)}
**Remaining Items**: 0
**Graph Edges**: {graph_edges}

## Processed Items

{"\n".join(processed_lines) if processed_lines else "- None yet"}

## Dependency Graph

{adj_str if adj_str else "- None configured"}

*Generated by Graph Loop - progress survives between runs*
"""
    
    PROGRESS_FILE.write_text(content)


def topological_sort(items, dependencies):
    """Sort items in topological order respecting dependencies.
    
    items: list of item identifiers
    dependencies: dict mapping item -> list of items it depends on
    
    Returns: (sorted_items, cycle_items) tuple
    """
    item_set = set(items)
    in_degree = {item: 0 for item in item_set}
    adj = defaultdict(list)
    
    for item, deps in dependencies.items():
        if item in item_set:
            for dep in deps:
                if dep in item_set:
                    adj[dep].append(item)
                    in_degree[item] += 1
    
    queue = deque([item for item in items if in_degree[item] == 0])
    sorted_items = []
    
    while queue:
        node = queue.popleft()
        sorted_items.append(node)
        for neighbor in adj[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)
    
    cycle_items = [item for item in items if item not in sorted_items]
    return sorted_items, cycle_items


def process_item(item_id):
    """Process a single item."""
    print(f"[Graph] Processing item {item_id}...")
    time.sleep(1)
    print(f"[Graph] Item {item_id} processed successfully")
    return True


def run_loop():
    """Graph loop that processes items respecting dependencies with spine memory."""
    print("=" * 60)
    print("Loop Engineering: Project 8 - Graph Loop")
    print("=" * 60)
    print()

    # Define the item graph for this run
    all_items = ["Item A", "Item B", "Item C", "Item D", "Item E"]
    # Dependency: Item C depends on Item A, Item D depends on Item B
    dependencies = {
        "Item C": ["Item A"],
        "Item D": ["Item B"],
    }

    # Load previous progress (spine memory)
    already_processed = load_processed_items()
    print(f"[Graph] Spine memory: {len(already_processed)} items previously processed")
    
    # Filter to only unprocessed items
    unprocessed = [item for item in all_items if item not in already_processed]
    
    print(f"[Graph] Item pool: {', '.join(all_items)}")
    print(f"[Graph] Dependencies: {dependencies}")
    print(f"[Graph] New/remaining items: {', '.join(unprocessed) if unprocessed else 'None - all done!'}")
    print()

    # Topological sort
    sorted_items, cycle_items = topological_sort(unprocessed, dependencies)
    
    print(f"[Graph] Topological order: {', '.join(sorted_items) if sorted_items else 'None'}")
    if cycle_items:
        print(f"[Graph] ⚠️ Cycle detected breaking: {', '.join(cycle_items)}")
    
    # Process items in order
    newly_processed = []
    
    for item in sorted_items:
        if process_item(item):
            newly_processed.append(item)
        time.sleep(POLL_INTERVAL)
    
    # Handle cycle items
    for item in cycle_items:
        print(f"[Graph] Skipping cycle item {item} (will be retried next run)")
        newly_processed.append(item)
    
    # Update spine with all processed items
    all_processed = already_processed | set(newly_processed)
    graph_adjacency = dependencies
    
    save_processed_items(all_processed, len(dependencies), graph_adjacency)
    
    # Report
    remaining = [item for item in all_items if item not in all_processed]
    
    print()
    print(f"[Graph] Summary: {len(newly_processed)} items processed this run")
    print(f"[Graph] Total processed: {len(all_processed)}/{len(all_items)}")
    print(f"[Graph] Remaining: {', '.join(remaining) if remaining else 'None'}")
    print()
    print("Progress remembered in progress.md (spine) for next run.")


if __name__ == "__main__":
    # NOTE: Do NOT delete progress.md here - we want spine memory to persist
    # across runs. The file will be overwritten with updated progress.
    run_loop()